# Generated by Django 3.0.6 on 2020-07-02 21:46

from django.db import migrations

def run_script(apps, schema_editor):
    const = apps.get_model('app', 'Aulas')
    const.objects.create(
        name="Full Cycle e Estudo de caso",
        description="https://youtu.be/MuWmfCDXFKU"
    )
    const.objects.create(
        name="Microsserviço de assinaturas com RabbitMQ e Golang Buffalo",
        description="https://youtu.be/2cHwTsI00uk"
    )
    const.objects.create(
        name="Serverless framework e processamento de pagamentos",
        description="https://youtu.be/gJZZ0E7wS58"
    )
    const.objects.create(
        name="Multi-tenancy applications com Django",
        description="https://youtu.be/8rLDB6QWSRQ"
    )
    const.objects.create(
        name="Ecommerce com Nest.js, Loopback e ElasticSearch",
        description=""
    )
    const.objects.create(
        name="Microsserviços em produção com Docker e Kubernetes",
        description=""
    )

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(run_script),
    ]
